.github/workflows/production.yml

small changes to CD to production

fix production link

---

.github/workflows/preview.yml

added logic for checking PR description

---

vercel.json

#22
added vercel config to handle redirect from vercel to react router dom

fix-vercel-redirection-from-any-page-to-root

---

.github/workflows/send-tg-message.yml

added TG bot workflow

---

.github/workflows/production.yml
.github/workflows/send-tg-message.yml
README.md

#35 updates for readme file and names of pipelines

#35 update readme file and name of pipelines

---

src/entities/category/hooks/useLoadCategories.ts
src/entities/category/model/selectors/selectSetCategories.ts
src/entities/category/model/selectors/selectUserCategories.ts
src/entities/category/model/store/useCategoryStore.ts
src/entities/category/ui/CategoriesGrid.tsx
src/entities/category/ui/CategoryCard.tsx
src/entities/paymentSource/hooks/useLoadPaymentSources.ts
src/entities/paymentSource/model/selectors/selectSetUserPaymentSources.ts
src/entities/paymentSource/model/selectors/selectUserPaymentSources.ts
src/entities/paymentSource/model/store/usePaymentSourcesStore.ts
src/entities/paymentSource/ui/PaymentSourcesCard.tsx
src/entities/paymentSource/ui/PaymentSourcesGrid.tsx
src/main.tsx
src/pages/CategoryPage/CategoryPage.tsx
src/pages/HomePage/HomePage.tsx
src/pages/PaymentSourcesPage/PaymentSourcesPage.tsx
src/pages/routes.tsx
src/shared/constants/routesEnum.ts
src/widgets/Forms/AddExpenseForm/AddCategoryForm.tsx
src/widgets/Forms/AddExpenseForm/AddPaymentSourceForm.tsx
src/widgets/Forms/AddExpenseForm/CategoriesSelect.tsx
src/widgets/Forms/AddExpenseForm/PaymentSourcesSelect.tsx

#32 Added new pages. as far as we don't have any links, this pages can be found with manual redirect to `/category` and `/payment-source`

#32 new-page-categories, new-page-payment-sources

---

src/widgets/Forms/Register/RegisterForm.tsx

#40 Added helpers for the registration field

40 Add helpers for registerForm

---

package.json
pnpm-lock.yaml
src/entities/expenses/ui/ExpenseItem.tsx
src/entities/user/model/types/TUserStore.ts
src/shared/api/accessControlApi.ts
src/shared/api/authApi.ts
src/shared/api/userApi.ts
src/utils/helpers/emailToHexColor.ts
src/widgets/Forms/Login/LoginForm.tsx
src/widgets/Forms/Register/RegisterForm.tsx
src/widgets/Forms/setNewPassword/setNewPasswordForm.tsx
src/widgets/Modal/ShareWithModal/ShareWithModal.tsx

#11
as far as we now have menu, share option is hidden there for now.

11 share option in expense menu

---

src/app/providers/Theme.tsx
src/entities/expenses/ui/ExpenseItem.tsx
src/entities/expenses/ui/ExpensesTable.tsx
src/pages/HomePage/HomePage.tsx
src/shared/hooks/useWindowWidth.ts
src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx
src/widgets/Forms/AddExpenseForm/HorizontalList.tsx

#56 
1.  add hook for dynamic check of width
2.  add adaptive for homepage
3.  small style fixes

facelift-of-mainpage

---

src/app/providers/Query.tsx
src/entities/expenses/ui/ExpenseItem.tsx
src/shared/api/rootApi.ts
src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx

#60 fixed reauth, replaced ustable grid with default one, fixed swipable list height

small fixes

---

src/entities/category/hooks/useLoadCategories.ts
src/entities/category/model/selectors/selectSetCategories.ts
src/entities/category/model/selectors/selectUserCategories.ts
src/entities/category/model/store/useCategoryStore.ts
src/entities/expenses/ui/ExpensesTable.tsx
src/utils/helpers/createSelectors.ts
src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx
src/widgets/Forms/AddExpenseForm/CategoriesSelect.tsx

#59 Added a function for generating selectors and replaced one of the stores as an example of how to use this function.

#59 auto generating selectors

---

src/utils/components/Navbar.tsx
src/widgets/Navigaton/DrawerNavigation/DrawerNavigation.tsx

#30 add drawer as temporary solution to change pages

30 add drawer as temporary solution to change pages

---

pnpm-lock.yaml
src/app/App.tsx
src/app/providers/MuiLocalizationProvider.tsx
src/entities/expenses/model/store/useExpensesStore.ts
src/entities/expenses/ui/ExpenseItem.tsx
src/entities/paymentSource/model/store/usePaymentSourcesStore.ts
src/pages/ExpensesMobilePage/ExpensesMobilePage.tsx
src/pages/HomePage/HomePage.tsx
src/pages/routes.tsx
src/shared/constants/Locales.ts
src/shared/constants/routesEnum.ts
src/utils/components/ContentContainer.tsx
src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx
src/widgets/Forms/AddExpenseForm/HorizontalList.tsx
src/widgets/Forms/Login/LoginForm.tsx
src/widgets/Forms/Register/RegisterForm.tsx
src/widgets/Forms/setNewPassword/setNewPasswordForm.tsx
src/widgets/Navigaton/DrawerNavigation/DrawerNavigation.tsx

homepage facelift

---

package.json
pnpm-lock.yaml
src/entities/expenses/ui/ExpenseItem.tsx
src/entities/expenses/ui/ExpensesTable.tsx
src/utils/components/ContentContainer.tsx
src/utils/components/FootBar.tsx
src/utils/components/Layout.tsx
src/utils/components/Navbar.tsx
src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx
vite.config.ts

#76 added new bottom navigation only for mobile and tablet devices. 
small ui fixes

#76 bottom-navigation-on-mobile-and-tablet

---

src/entities/expenses/ui/expensesQueryForm.tsx
src/entities/filters/models/store/FiltersStore.ts
src/entities/filters/models/types/types.ts
src/pages/HomePage/HomePage.tsx

filters added

---

package.json
src/entities/expenses/ui/SpentThisMonth.tsx
src/pages/ExpensesMobilePage/ExpensesListMobilePage.tsx
src/pages/HomePage/HomePage.tsx
src/pages/routes.tsx
src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx

#83
fixed Clear button in calculator
fixed floating point JS error when calculating this month expenses
as far as logic with spent this month logic is now in two point, moved it to component and reused it.

clear-on-calculator-is-broken

---

package.json
src/entities/category/ui/CategoryCard.tsx
src/entities/expenses/ui/ExpensesTable.tsx
src/entities/expenses/ui/SpentThisMonth.tsx
src/entities/expenses/ui/expensesQueryForm.tsx
src/entities/paymentSource/ui/PaymentSourcesCard.tsx
src/pages/ExpensesMobilePage/ExpensesListMobilePage.tsx
src/pages/HomePage/HomePage.tsx
src/utils/components/ContentContainer.tsx

#88 
1. updated expenses filter logic (added useCallback, moved all logic inside component)
2. small ui fixes for categories and payment sources
3. laptopversion facelift - now calculator and filter and spend this month are always on top, expenses list is scrollable.

fix-broken-filter

---

package.json
src/entities/expenses/ui/ExpenseItem.tsx
src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx
src/widgets/Modal/ExpenseModal/ExpenseModal.tsx
src/widgets/Modal/ModalWrapper.tsx

#82 
added logic for opening modal window only on screens bigger then tablet
added logic for clearing state after update expense modal is closed/cleared button is pressed
small ui fixes for modal (added blur for modal wrapper)

reset-calculator-when-closing-modal

---

package.json
pnpm-lock.yaml
src/utils/components/Navbar.tsx
src/widgets/NavBarMenu/NavBarMenu.tsx

67 feauture menu for nav bar from main

---

src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx

97 feauture add helpet text for save expense button from main

---

.github/workflows/playwright.yml
.github/workflows/preview.yml
.gitignore
package.json
playwright.config.ts
pnpm-lock.yaml
src/utils/hooks/useDebouncedValue.ts
src/utils/hooks/useLongPress.ts
tests/login.spec.ts

added playwright and login test

---

.eslintrc.cjs
package.json
src/entities/user/ui/Profile.tsx
src/widgets/Forms/Register/RegisterForm.tsx
src/widgets/Forms/setNewPassword/setNewPasswordForm.tsx

#111 
added logic to redirect after success login. still need some backend updates to redirect after confirm email from link.

Redirect after register, reset password, email confirm (via manual code enter)

---

src/app/providers/MuiLocalizationProvider.tsx
src/entities/accessControl/ui/AccessControlItem.tsx
src/entities/category/hooks/useLoadCategories.ts
src/entities/category/ui/CategoriesGrid.tsx
src/entities/category/ui/UpsertCategoryForm.tsx
src/entities/expenses/hooks/useLoadExpenses.ts
src/entities/expenses/ui/ExpenseItem.tsx
src/entities/expenses/ui/ExpenseItemMenu.tsx
src/entities/expenses/ui/ExpensesDayGroup.tsx
src/entities/expenses/ui/ExpensesTable.tsx
src/entities/expenses/ui/SpentThisMonth.tsx
src/entities/paymentSource/hooks/useLoadPaymentSources.ts
src/entities/paymentSource/ui/PaymentSourcesGrid.tsx
src/entities/paymentSource/ui/UpsertPaymentSourceForm.tsx
src/entities/user/ui/Profile.tsx
src/entities/user/ui/ProfilePhotoUploader.tsx
src/entities/userSettings/ui/Settings.tsx
src/shared/api/expenseApi.ts
src/shared/api/rootApi.ts
src/utils/components/Redirector.tsx
src/utils/errorHandler.ts
src/utils/helpers/calculateTotalAmmount.ts
src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx
src/widgets/Forms/setNewPassword/setNewPasswordForm.tsx

feat: Exchange rates are currently used to recalculate expenses in different currencies

---

src/entities/userSettings/ui/Settings.tsx

fix-user-confId

---

src/entities/expenses/ui/ExpenseItem.tsx

observe names/colours for expenses/payment sources depending on user settings

---

.github/workflows/copy-to-vps.yml
.github/workflows/production.yml
src/shared/api/rootApi.ts

132 create deploy to vps

---

src/app/providers/Theme.tsx
src/entities/userSettings/model/store/useUserSettingsStore.ts
src/entities/userSettings/ui/Settings.tsx

#125
added able to Get default theme from user

default theme from user settings

---

src/entities/expenses/ui/ExpensesDayGroup.tsx
src/entities/expenses/ui/SpentThisMonth.tsx
src/utils/helpers/calculateTotalAmmount.ts
src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx

#124 add default-currency from user config

add default-currency from user config. fix some lexical mistakes

---

src/entities/expenses/ui/SpentThisMonth.tsx
src/pages/HomePage/HomePage.tsx
src/utils/components/ContentContainer.tsx
src/utils/components/FootBar.tsx

#142 
added "spent this month" into all devices. added adaptation styles

spent this month is now shown on all devices

---

src/pages/CategoryPage/CategoryPage.tsx
src/pages/PaymentSourcesPage/PaymentSourcesPage.tsx

#128 implemented button for hot-create paymentSources/category on corresponding pages

#128 create-category-btn

---

locales/en/translation.json
locales/ru/translation.json
src/entities/category/ui/CategoriesGrid.tsx
src/entities/paymentSource/ui/PaymentSourcesGrid.tsx
src/pages/CategoryPage/CategoryPage.tsx
src/pages/PaymentSourcesPage/PaymentSourcesPage.tsx
src/widgets/HorizontalList/HorizontalList.tsx
src/widgets/HorizontalList/HorizontalListItem.tsx
src/widgets/Modal/DeleteCategoryDialog.tsx

#134 added modal window before category/payment element would delete

#134 source/catecory delete modal window

---

locales/en/translation.json
locales/ru/translation.json
src/entities/category/ui/CategoryCard.tsx
src/entities/expenses/ui/ExpensesTable.tsx
src/entities/expenses/ui/SpentThisMonth.tsx
src/entities/expenses/ui/expensesQueryForm.tsx
src/entities/paymentSource/ui/PaymentSourcesCard.tsx
src/entities/user/ui/Profile.tsx
src/entities/userSettings/hooks/useLoadConfig.ts
src/pages/HomePage/HomePage.tsx
src/utils/components/ContentContainer.tsx
src/utils/components/Layout.tsx
src/utils/components/UnverifiedAlert.tsx
src/widgets/Forms/AddExpenseForm/AddExpenseCalc.tsx
src/widgets/HorizontalList/HorizontalList.tsx
src/widgets/HorizontalList/HorizontalListItem.tsx
src/widgets/ItemMenu/ItemMenu.tsx
src/widgets/NavBarMenu/NavBarMenu.tsx

#117  prevent unverified users requests able

#117 prevent unverified users requests able

---

.github/workflows/bump-package-version.yml

#149 implement automated version bump

#149 implement automated version bump

---

.github/workflows/bump-package-version.yml

#149 fix workflow error with direct push into protected branch

#149 change config in bump-package-version.yml

---

.github/workflows/bump-package-version.yml

#149 change config in bump-package-version.yml (second iteration)

#149 change config in bump-package-version.yml (second iteration)

---

src/widgets/NavBarMenu/NavBarMenu.tsx

#154 
fix: close menu after navigate to profile page

Close menu after navigate to profile page

---

src/entities/expenses/hooks/useLoadExpenses.ts
src/entities/expenses/ui/ExpensesTable.tsx
src/entities/expenses/ui/expensesQueryForm.tsx

#157 
fix: reset filters on add expense

Don't reset filters on add expense

---

src/entities/expenses/ui/ExpensesTable.tsx

fix skeletons while the user is unverified

fix skeletons 

---

package.json
pnpm-lock.yaml
src/entities/category/hooks/useUpdateCategoryOrder.ts
src/entities/category/ui/CategoriesGrid.tsx
src/entities/category/ui/CategoryCard.tsx
src/entities/paymentSource/hooks/useUpdatePaymentSourcesOrder.ts
src/entities/paymentSource/ui/PaymentSourcesCard.tsx
src/entities/paymentSource/ui/PaymentSourcesGrid.tsx
src/pages/CategoryPage/CategoryPage.tsx
src/pages/PaymentSourcesPage/PaymentSourcesPage.tsx
src/shared/api/categoryApi.ts
src/shared/api/paymentsSourceApi.ts

- add drag&drop to payment sources
- add drag&drop for categories
#150

Make Payment Source and Categories drag and drop

---

locales/ru/profile.json
src/entities/user/ui/Profile.tsx

Fix in profile translation

---

src/utils/components/Loader.spec.tsx
src/utils/components/Loader.tsx
src/utils/components/__snapshots__/Loader.spec.tsx.snap

- add unit tests and snapshot test
- update snapshot
close #209

Make tests for Loader component

---

package.json
src/shared/themes/darkTheme.css
src/shared/themes/lightTheme.css
src/shared/ui-kit/IconButton/IconButton.tsx
src/utils/components/FootBar.tsx

icons styles  were synchronized with app theme

fix(icons): icons styles were fixed
